name: media-extractor

services:
  me-pg:
    image: postgres:17.2
    container_name: me-pg
    restart: no
    healthcheck:
      test: "psql -U root me-database -c ''"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      POSTGRES_MULTIPLE_DATABASES: me_database
    volumes:
      - me-pg-data:/var/lib/postgresql
      - ./postgres:/docker-entrypoint-initdb.d


volumes:
  me-pg-data:
    name: me-pg-data
